### ISSUE TITLE
Create Standard Lists

### ISSUE THREAD

**Issue by paddykontschak** [romancm/gamebrary#176]
# 🌟 Feature
Standardlists would greet the user with a set of predefined lists so they have a quicker start setting up a new account/gameboard.

## Proposed lists:
- Currently Playing
- Backlog
- Completed
- Wishlist

## Tasks
- [ ] user opens game board of platform that doesn't have any lists yet
  - [ ] game board already displays the standard lists
    - [ ] Currently Playing
    - [ ] Backlog
    - [ ] Completed
    - [ ] Wishlist
- [ ] user opens game board of platform that already has lists
  - [ ] game board checks if the standard lists exist
    - [ ] case insensitive and similar naming check in a reasonable scope (`currently playing`, `currently Playing`, `playing`)
  - [ ] game board tells the user that standard lists weren't found and suggests adding them (in some not annoying way e.g. "Are you currently playing some games? Why not [add a new list] for that" rather than "No standard lists found. Create them now?")
  - [ ] user should have option to dismiss the suggestions per game board (close a suggestion, don't show it again)
  - [ ] user should have option to dismiss the suggestions globally ("show/hide tips/suggestions")

**Comment by paddykontschak** [comment]
- [ ] user opens game board of platform that doesn't have any lists yet
  - [ ] game board already displays the standard lists
    - [ ] Currently Playing
    - [ ] Backlog
    - [ ] Completed
    - [ ] Wishlist
- [ ] user opens game board of platform that already has lists
  - [ ] game board checks if the standard lists exist
    - [ ] case insensitive and similar naming check in a reasonable scope (`currently playing`, `currently Playing`, `playing`)
  - [ ] game board tells the user that standard lists weren't found and suggests adding them (in some not annoying way e.g. "Are you currently playing some games? Why not [add a new list] for that" rather than "No standard lists found. Create them now?")
  - [ ] user should have option to dismiss the suggestions per game board (close a suggestion, don't show it again)
  - [ ] user should have option to dismiss the suggestions globally ("show/hide tips/suggestions")
